### ISSUE TITLE
Unable to pull/push via rsync if git-fat submodule has path with spaces in it

### ISSUE THREAD

**Issue by stemann** [cyaninc/git-fat#28]
Say a main repo. A refers to a submodule B, but the path to submodule B includes spaces:
A/Data Sets/B

then git fat pull (with an rsync remote) fails, as the path is not correctly quoted for the call to rsync.

Problem relevant for current release 0.3.4.

**Comment by justinclift** [comment]
Fixed?

**Comment by CzarekTomczak** [comment]
The issue is when splitting cmd_tmpl by spaces: https://github.com/cyaninc/git-fat/blob/develop/git_fat/git_fat.py#L369
As src/dst may contain spaces it will split these paths in half which causes issue. The solution would be to split cmd_tmpl and only then append src/dst to the cmd list.

**Comment by abraithwaite** [comment]
I thought I had fixed this in develop but it's apparent that's not the case.

I just got back from vacation so I should have more time to catch up with the changes and do a release.

**Comment by abraithwaite** [comment]
Just an update on this:  I got back from vacation 2 weeks ago, but haven't had a lot of time because I was looking for a new place.  I just finished moving into the new place this weekend so I should be able to get through the backlog.

**Comment by justinclift** [comment]
No worries at all.  I know what that's like, recently having moved myself. :wink:
