### ISSUE TITLE
Any ideas on why Restore x -> y is so slow on windows?

### ISSUE THREAD

**Issue by ajohnson23** [cyaninc/git-fat#37]
Firstly, does anyone else observe that the Restore x -> y steps are much slower on windows than linux? If so, before I dive in and start profiling, I was wondering if others have figured out why this is the case and if there are any ideas on how to speed it up. Thanks!

**Comment by justinclift** [comment]
@CzarekTomczak may know, as he's been doing stuff with the Windows side of things. :smile:

**Comment by CzarekTomczak** [comment]
Some git functions may be slower on Windows, as git on Windows is not a native port, it uses many linux tools in the form of msysgit libraries. Add to it that the latest stable release for Win is git 1.9.5 and for Linux it is git 2.2.2 I believe. And "so slow" is not much of a precise measurement. Provide us some numbers.

**Comment by CzarekTomczak** [comment]
It would be nice to provide us with some numbers. In my testing I didn't notice much differences between Linux and Windows, but I was testing only cloning of the whole repository (1GB). It took much time on both Linux and Windows as it was running through slow VPN.

**Comment by CzarekTomczak** [comment]
I wrote my last comment in a wrong way. I didn't mean that I was testing only cloning. I noticed much slowness only during cloning, but it was connection. In general git on Windows is slower from my experience.

**Comment by ajohnson23** [comment]
I will grab some numbers and post them soon.

**Comment by abraithwaite** [comment]
This one's difficult.  I don't have a windows machine so I can't comment either way.

**Comment by ajohnson23** [comment]
One thing I was curious on --
Is the Restore X -> Y step essentially a file copy (from the fat/objects to the working copy)?
Does it happen through a pipe on account of git clean/smudge, or does it happen via shutils.* methods?
If so, does it have to happen through a pipe?

I ask because of things like this - http://stackoverflow.com/questions/21799210/python-copy-larger-file-too-slow
shutil.copy and the like is not known to be very quick, so we could seek alternatives such as using xcopy if that's what's slowing us down. Unfortunately, I believe the Restore step happens through git getting the stdin from git-fat rather than shutil.copy, but I just wanted to confirm.

I'll be back with some numbers later when I boot back into linux.

**Comment by abraithwaite** [comment]
The way that git filters work, you read directly from the instream and write directly to the outstream.  That means for a smudge, you read in the placeholder file and you write out the actual file.  For clean, you read in the actual file and write out the placeholder.

Knowing this and what Czarek mentioned, I don't think it can be easily optimized but I'm open to suggestions.

**Comment by ajohnson23** [comment]
That's what I feared. I don't know of a way to optimize it offhand either, but I'll keep it in mind.
One question as I think about this more. If, after doing a "git fat pull", I immediately do another "git fat pull", naturally it doesn't need to re-read every place holder file and re-write every actual file again. What allows it to do this?

**Comment by abraithwaite** [comment]
We let git handle that mostly.  It should only call filter-clean and filter-smudge for files that have changed but it's kinda funky.

From my comment in the source:

>  The output of our smudge filter depends on the existence of
  the file in .git/fat/objects, but git caches the file stat
  from the previous time the file was smudged, therefore it
  won't try to re-smudge. There's no git command to specifically
  invalidate the index cache so we have two options:
  Change the file stat mtime or change the file size. However, since
  the file mtime only has a granularity of 1s, if we're doing a pull
 right after a clone or checkout, it's possible that the modified
 time will be the same as in the index. Git knows this can happen
 so git checks the file size if the modified time is the same.
 The easiest way around this is just to remove the file we want
 to replace (since it's an orphan, it should be a placeholder)

**Comment by abraithwaite** [comment]
To answer more directly though: since the real files in the tree have the same `os.stat` and size, git won't call it's filters.  So after a pull we call `checkout` which searches for all the orphans in the working tree and replaces them.  We pass over files which are not placeholders.

**Comment by ajohnson23** [comment]
Hah, I was just reading that comment!
So... perhaps a pre-pull process that copies actual files over placeholders ahead of time (using a presumably faster IO method native to windows such as the xcopy command), then tricks git into thinking it doesn't need to resmudge. This could require directly mucking with the git index?

Or something like that. Does this make any sense? I'm willing to jump on this, but want to make sure this is a somewhat sane idea.

**Comment by ajohnson23** [comment]
linux git fat pull:
real	0m23.209s
windows git fat pull:
real    1m5.861s
So yeah, quite significant. Note that the rsync part is pretty much instant on both of these, so both of these times are mostly the Restore X -> Y part. This is on a gigabit lan, both on the same machine (Dual boot), and both to SSDs.

For reference, the command looks like this (git server hostname is changed since it's internal):
git clone -b draster git.example.org:FreeRDP ftest ; pushd ftest ; git fat init ; time git fat pull ; popd

**Comment by CzarekTomczak** [comment]
@ajohnson23 Have you tried setting some optimization flags on Windows? By googling "git slow windows" found [this stackoverflow answer](http://stackoverflow.com/a/24045966/623622). One of the options worth trying: 
`core.preloadindex` - does filesystem operations in parallel to hide latency 
and will be enabled by default in future versions of git on all platforms
(update: enabled in v2.1).

For the speed comparison test to be fair you should be comparing using the same git versions. Try installing an old git 1.9.5 on Linux, which is the latest release available on Windows. Maybe if we're lucky and that version proves to be slow on Linux, then the solution would be to wait for the 2.x release on Windows.

**Comment by ajohnson23** [comment]
Tried the following:
$ git config --global core.preloadindex true
$ git config --global core.fscache true
$ git config --global gc.auto 256
With unfortunately similar results. Running git bash as admin also yielded similar results.

I will try with the older git on linux, but I'm not hopeful on that.

**Comment by ajohnson23** [comment]
@CzarekTomczak 
I tried the following:
$ git config --global core.preloadindex true
$ git config --global core.fscache true
$ git config --global gc.auto 256
With unfortunately similar results. Running git bash as admin also yielded similar results.

I will try with the older git on linux, but I'm not hopeful on that.

**Comment by ajohnson23** [comment]
@CzarekTomczak On linux now, realized I'm still on git 1.9.1 there, so I'm actually apples to apples for that already.

I'd like to do some profiling of git itself on windows. Does anyone make git builds for windows available that have pdb files? I'd rather not have to build it myself if I can help it.

**Comment by ajohnson23** [comment]
For reference, changing _filter_smudge function to simply do this and nothing else:
print("good times!")

Yields the following time:
real    0m52.189s
Versus the normal timing of around 1m5s
(By doing this, I'm presumably cutting out the read from stdin/write to stdout from git-fat entirely)

So there's a 12 second hit there for the read/write, or around 20% I believe. Not insignificant, but not as dramatic as I'd hoped.

**Comment by ajohnson23** [comment]
Just to drive this home -- what my previous numbers most likely mean is that this is only (roughly) 20% a git-fat problem, and the remaining 80% of slowness is a general "git on windows is pretty slow" problem, since git is the thing responsible for traversing the index and running the smudge filter on the objects in it.

Here's an oldie but a goodie from Linux himself:
http://article.gmane.org/gmane.comp.version-control.git/53705

In summary, I don't think there's very much we can do to git-fat to improve this situation. We might eek out 10% by doing some weird file copy scheme prior to filter-smudge, but that's not going to help much in the overall scheme of things, and would probably hurt the maintainability and futureproofness of the code more than its worth.

So with that said I'm going to close my own issue. Thanks for helping and listening. I may drop back in later for some other overall git performance numbers later just for reference.

**Comment by ajohnson23** [comment]
Another data point:

In previous tests, I had only removed the contents of the _filter_smudge function. _filter_clean is also used during the git fat pull process, so I replaced the contents of both functions with a single print statement and reran the test:
real    0m44.210s

So _filter_smudge and _filter_clean combined make up about 33% of the time taken by git fat pull in this particular case.
