### ISSUE TITLE
"git-fat init" should add a pre-push hook that runs "git-fat push"

### ISSUE THREAD

**Issue by OptiverTimAll** [cyaninc/git-fat#55]
I've been investigating git large-file storage solutions, and while git-fat is more generally useful, GitHub's git-lfs is a bit nicer to use. One reason is that you don't have to manually "git lfs push" when you "git push", because when git-lfs installs its filters, it also installs a pre-push hook that automatically runs "git-lfs push".

Since the user wouldn't run "git push" if they didn't already expect to have a network connection, it should be safe for "git-fat init" to always set up a pre-push hook that runs "git-fat push".

**Comment by abraithwaite** [comment]
Yep.  This is what we did at Cyan.   We didn't open source it though because we had some other stuff in the hook.  I definitely would welcome a contribution of hooks though!

**Comment by abraithwaite** [comment]
Going to close this and copy your comment to #7.
