### ISSUE TITLE
Why doesn't 'git fat pull' run 'git fat init'?

### ISSUE THREAD

**Issue by AndrewJDR** [cyaninc/git-fat#63]
Why doesn't 'git fat pull' run 'git fat init'?

**Comment by abraithwaite** [comment]
`init` just calls `configure` internally.  `init` was kept as a convenience method for api compatibility, but `configure` is actually called for every git-fat operation.

https://github.com/cyaninc/git-fat/blob/develop/git_fat/git_fat.py#L467

Lemme know if there's some odd behavior in particular that you're seeing and I can take a look.

**Comment by AndrewJDR** [comment]
Oops, I think I was remembering this being an issue on the jedibrown version, as I vaguely remember always having to run git  fat init before doing git fat pull. I didn't realize it had been fixed on this fork :) Thanks for the clarification.
